import { useEffect } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useTypedSelector } from "@/app/hook";
import { AUTH_ROUTES, PROTECTED_ROUTES } from "@/routes/common/routePath";
import Logo from "@/components/logo/logo";
import dashboardImg from "@/assets/images/dashboard.png";
import dashboardDarkImg from "@/assets/images/dashboard_dark.png";
import { useTheme } from "@/context/theme-provider";
import {
  BarChart3,
  CreditCard,
  FileText,
  Repeat,
  Target,
  TrendingUp,
  ArrowRight,
  CheckCircle2,
  Shield,
  Zap,
  PieChart,
  Bell,
  Download,
  ChevronRight,
} from "lucide-react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const features = [
  {
    icon: BarChart3,
    title: "Smart Dashboard",
    description: "Get a bird's-eye view of your finances with income, expenses, balance, and savings rate at a glance.",
  },
  {
    icon: CreditCard,
    title: "Budget Management",
    description: "Set budgets per category with rollover support. Get alerts before you overspend.",
  },
  {
    icon: FileText,
    title: "AI-Powered Reports",
    description: "Receive monthly financial reports generated by AI with personalized insights.",
  },
  {
    icon: Repeat,
    title: "Recurring Transactions",
    description: "Automate regular expenses and income. Set it once and let Finora handle the rest.",
  },
  {
    icon: Target,
    title: "Savings Goals",
    description: "Track progress towards financial goals with visual milestones.",
  },
  {
    icon: Download,
    title: "CSV Import & Export",
    description: "Bulk import from spreadsheets and export for tax season.",
  },
  {
    icon: PieChart,
    title: "Category Analytics",
    description: "See exactly where your money goes with detailed category breakdowns.",
  },
  {
    icon: Bell,
    title: "Budget Alerts",
    description: "Get notified when you're approaching or exceeding your budget limits.",
  },
  {
    icon: Shield,
    title: "Secure & Private",
    description: "Your data is protected with industry-standard encryption.",
  },
  {
    icon: Zap,
    title: "Receipt Scanner",
    description: "Snap a photo of your receipt and let AI extract transaction details.",
  },
];

const faqs = [
  {
    question: "Is Finora free to use?",
    answer: "Yes! Finora is completely free. Track unlimited transactions, set unlimited budgets, and receive AI-powered monthly reports at no cost.",
  },
  {
    question: "How does the receipt scanner work?",
    answer: "Simply upload a photo of your receipt and our AI (powered by Google Gemini) will automatically extract the merchant, amount, date, and category. You can then review and save the transaction.",
  },
  {
    question: "Can I import transactions from a spreadsheet?",
    answer: "Absolutely! Finora supports CSV imports. You can bulk import up to 300 transactions at once with fields like title, amount, type, date, category, and payment method.",
  },
  {
    question: "What are recurring transactions?",
    answer: "Recurring transactions let you automate regular payments like rent, subscriptions, or salary. Set the amount, frequency (daily, weekly, monthly, yearly), and Finora will create them automatically.",
  },
  {
    question: "Does Finora support budget rollover?",
    answer: "Yes! You can enable budget rollover on any category. Up to 50% of your unused budget carries over to the next month, helping you plan better.",
  },
  {
    question: "How are my monthly reports generated?",
    answer: "At the end of each month, our AI analyzes your spending patterns, income trends, and savings rate to generate a personalized financial report with actionable insights.",
  },
  {
    question: "Is my financial data secure?",
    answer: "Your data is encrypted with bcrypt for passwords and JWT for session management. We use HTTPS, security headers, and never share your data with third parties.",
  },
];

const Landing = () => {
  const navigate = useNavigate();
  const { accessToken, user } = useTypedSelector((state) => state.auth);
  const { theme } = useTheme();

  useEffect(() => {
    if (accessToken && user) {
      navigate(PROTECTED_ROUTES.OVERVIEW, { replace: true });
    }
  }, [accessToken, user, navigate]);

  const dashboardScreenshot = theme === "dark" ? dashboardDarkImg : dashboardImg;

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="fixed top-0 left-0 right-0 z-50 border-b bg-background/80 backdrop-blur-sm">
        <div className="container mx-auto flex h-16 items-center justify-between px-4">
          <Logo url="/" />
          <div className="flex items-center gap-3">
            <Link
              to={AUTH_ROUTES.SIGN_IN}
              className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
            >
              Sign In
            </Link>
            <Link
              to={AUTH_ROUTES.SIGN_UP}
              className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 transition-colors"
            >
              Get Started
            </Link>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="container mx-auto px-4 pt-28 pb-16 md:pt-36 md:pb-24">
        <div className="mx-auto max-w-4xl text-center">
          <div className="inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1 text-sm text-primary mb-6">
            <CheckCircle2 className="h-4 w-4" />
            <span>Free personal finance tracker — No credit card required</span>
          </div>
          <h1 className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl lg:text-7xl text-foreground">
            Master your money
            <span className="block text-primary">with Finora</span>
          </h1>
          <p className="mt-6 text-lg text-muted-foreground max-w-2xl mx-auto leading-relaxed">
            Track expenses, set budgets, scan receipts, and get AI-powered financial insights — 
            all in one beautiful, modern app built to simplify your financial life.
          </p>
          <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link
              to={AUTH_ROUTES.SIGN_UP}
              className="inline-flex items-center gap-2 rounded-md bg-primary px-6 py-3 text-base font-medium text-primary-foreground hover:bg-primary/90 transition-colors w-full sm:w-auto justify-center"
            >
              Start Tracking for Free
              <ArrowRight className="h-4 w-4" />
            </Link>
            <Link
              to={AUTH_ROUTES.SIGN_IN}
              className="inline-flex items-center gap-2 rounded-md border border-border bg-background px-6 py-3 text-base font-medium text-foreground hover:bg-accent transition-colors w-full sm:w-auto justify-center"
            >
              Sign In
              <ChevronRight className="h-4 w-4" />
            </Link>
          </div>
        </div>
      </section>

      {/* Dashboard Screenshot */}
      <section className="container mx-auto px-4 pb-20">
        <div className="mx-auto max-w-5xl rounded-xl border border-border overflow-hidden shadow-2xl">
          <div className="bg-card border-b border-border px-4 py-2 flex items-center gap-2">
            <div className="flex gap-1.5">
              <div className="h-3 w-3 rounded-full bg-destructive" />
              <div className="h-3 w-3 rounded-full bg-warning" />
              <div className="h-3 w-3 rounded-full bg-success" />
            </div>
            <span className="text-xs text-muted-foreground ml-2">finora.app/overview</span>
          </div>
          <img
            src={dashboardScreenshot}
            alt="Finora Dashboard"
            className="w-full h-auto"
          />
        </div>
      </section>

      {/* Stats Bar */}
      <section className="border-y bg-muted/30">
        <div className="container mx-auto px-4 py-12">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
            <div>
              <div className="text-3xl font-bold text-primary">12+</div>
              <div className="mt-1 text-sm text-muted-foreground">Expense Categories</div>
            </div>
            <div>
              <div className="text-3xl font-bold text-primary">6</div>
              <div className="mt-1 text-sm text-muted-foreground">Payment Methods</div>
            </div>
            <div>
              <div className="text-3xl font-bold text-primary">AI</div>
              <div className="mt-1 text-sm text-muted-foreground">Powered Reports</div>
            </div>
            <div>
              <div className="text-3xl font-bold text-primary">300</div>
              <div className="mt-1 text-sm text-muted-foreground">CSV Bulk Import</div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="container mx-auto px-4 py-20">
        <div className="mx-auto max-w-2xl text-center mb-12">
          <h2 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
            Everything you need to manage your money
          </h2>
          <p className="mt-4 text-lg text-muted-foreground">
            Powerful features to help you track, plan, and grow your finances with confidence.
          </p>
        </div>
        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((feature) => (
            <div
              key={feature.title}
              className="rounded-xl border border-border bg-card p-6 shadow-sm hover:shadow-md transition-shadow hover:border-primary/30"
            >
              <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10">
                <feature.icon className="h-6 w-6 text-primary" />
              </div>
              <h3 className="mt-4 text-lg font-semibold text-foreground">
                {feature.title}
              </h3>
              <p className="mt-2 text-sm text-muted-foreground leading-relaxed">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* App Showcase */}
      <section className="container mx-auto px-4 py-20">
        <div className="mx-auto max-w-2xl text-center mb-12">
          <h2 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
            See Finora in action
          </h2>
          <p className="mt-4 text-lg text-muted-foreground">
            A clean, intuitive interface designed for everyday use.
          </p>
        </div>
        <div className="mx-auto max-w-5xl rounded-xl border border-border overflow-hidden shadow-2xl">
          <div className="bg-card border-b border-border px-4 py-2 flex items-center gap-2">
            <div className="flex gap-1.5">
              <div className="h-3 w-3 rounded-full bg-destructive" />
              <div className="h-3 w-3 rounded-full bg-warning" />
              <div className="h-3 w-3 rounded-full bg-success" />
            </div>
            <span className="text-xs text-muted-foreground ml-2">finora.app/dashboard</span>
          </div>
          <img
            src={dashboardScreenshot}
            alt="Finora App Screenshot"
            className="w-full h-auto"
          />
        </div>
      </section>

      {/* FAQ Section */}
      <section className="container mx-auto px-4 py-20">
        <div className="mx-auto max-w-2xl text-center mb-12">
          <h2 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
            Frequently asked questions
          </h2>
          <p className="mt-4 text-lg text-muted-foreground">
            Everything you need to know about Finora.
          </p>
        </div>
        <div className="mx-auto max-w-3xl">
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`}>
                <AccordionTrigger className="text-left">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground leading-relaxed">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>

      {/* CTA Section */}
      <section className="container mx-auto px-4 pb-20">
        <div className="mx-auto max-w-3xl rounded-2xl border border-border bg-card p-8 text-center sm:p-12 relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-primary/5 to-transparent" />
          <div className="relative">
            <h2 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
              Ready to take control of your finances?
            </h2>
            <p className="mt-4 text-muted-foreground">
              Start tracking your income and expenses today. No credit card required.
            </p>
            <div className="mt-6 flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link
                to={AUTH_ROUTES.SIGN_UP}
                className="inline-flex items-center gap-2 rounded-md bg-primary px-8 py-3 text-base font-medium text-primary-foreground hover:bg-primary/90 transition-colors"
              >
                Start for Free
                <ArrowRight className="h-4 w-4" />
              </Link>
              <Link
                to={AUTH_ROUTES.SIGN_IN}
                className="inline-flex items-center gap-2 rounded-md border border-border bg-background px-6 py-3 text-base font-medium text-foreground hover:bg-accent transition-colors"
              >
                Sign In
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t py-8">
        <div className="container mx-auto px-4 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <Logo url="/" />
          </div>
          <p className="text-sm text-muted-foreground">
            &copy; {new Date().getFullYear()} Finora. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
};

export default Landing;
