import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { format } from "date-fns";
import {
  FileText,
  Loader2,
  Download,
  Mail,
  CheckCircle2,
  AlertCircle,
} from "lucide-react";
import { useGenerateReportQuery } from "@/features/report/reportAPI";
import { toast } from "sonner";

const GenerateReportDialog = () => {
  const [open, setOpen] = useState(false);
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");
  const [reportGenerated, setReportGenerated] = useState(false);

  const { data: reportData, refetch, isFetching, isError } = useGenerateReportQuery(
    { from: fromDate, to: toDate },
    {
      skip: true,
    }
  );

  const handleGenerate = async () => {
    if (!fromDate || !toDate) {
      toast.error("Please select both dates");
      return;
    }
    setReportGenerated(false);
    try {
      const result = await refetch();
      if (result.data) {
        setReportGenerated(true);
      } else {
        setReportGenerated(true);
      }
    } catch (error) {
      console.error(error);
      setReportGenerated(true);
    }
  };

  const handleDownload = () => {
    if (!reportData) return;
    const reportText = generateTextReport(reportData);
    const blob = new Blob([reportText], { type: "text/plain;charset=utf-8;" });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `financial-report-${fromDate}-to-${toDate}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  const generateTextReport = (data: any) => {
    const { period, summary, insights } = data;
    let text = `FINANCIAL REPORT\n`;
    text += `${"=".repeat(40)}\n`;
    text += `Period: ${period}\n`;
    text += `Generated: ${format(new Date(), "MMMM d, yyyy")}\n`;
    text += `${"=".repeat(40)}\n\n`;
    
    text += `SUMMARY\n`;
    text += `${"-".repeat(40)}\n`;
    text += `Total Income:   $${summary?.income?.toLocaleString() || 0}\n`;
    text += `Total Expenses: $${summary?.expenses?.toLocaleString() || 0}\n`;
    text += `Balance:       $${summary?.balance?.toLocaleString() || 0}\n`;
    text += `Savings Rate:   ${summary?.savingsRate || 0}%\n\n`;
    
    if (summary?.topCategories?.length > 0) {
      text += `TOP EXPENSE CATEGORIES\n`;
      text += `${"-".repeat(40)}\n`;
      summary.topCategories.forEach((cat: any) => {
        text += `${cat.name}: $${cat.amount?.toLocaleString()} (${cat.percent}%)\n`;
      });
      text += `\n`;
    }
    
    if (insights?.length > 0) {
      text += `INSIGHTS\n`;
      text += `${"-".repeat(40)}\n`;
      insights.forEach((insight: any, idx: number) => {
        text += `${idx + 1}. ${insight.title}\n`;
        text += `   ${insight.description}\n\n`;
      });
    }
    
    text += `${"=".repeat(40)}\n`;
    text += `Generated by Finora\n`;
    return text;
  };

  const resetForm = () => {
    setFromDate("");
    setToDate("");
    setReportGenerated(false);
  };

  const handleOpenChange = (isOpen: boolean) => {
    if (!isOpen) resetForm();
    setOpen(isOpen);
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogTrigger asChild>
        <Button variant="outline" className="!px-6">
          <FileText className="h-4 w-4" />
          <span>Generate Report</span>
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Generate Report</DialogTitle>
        </DialogHeader>

        <div className="space-y-6">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="from-date">From Date</Label>
              <Input
                id="from-date"
                type="date"
                value={fromDate}
                onChange={(e) => setFromDate(e.target.value)}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="to-date">To Date</Label>
              <Input
                id="to-date"
                type="date"
                value={toDate}
                onChange={(e) => setToDate(e.target.value)}
              />
            </div>
          </div>

          <Button
            className="w-full"
            onClick={handleGenerate}
            disabled={!fromDate || !toDate || isFetching}
          >
            {isFetching ? (
              <Loader2 className="h-4 w-4 animate-spin mr-2" />
            ) : (
              <FileText className="h-4 w-4 mr-2" />
            )}
            Generate Report
          </Button>

          {reportGenerated && reportData && (
            <div className="space-y-4 pt-4 border-t">
              <div className="flex items-center gap-2 text-success">
                <CheckCircle2 className="h-4 w-4" />
                <span className="text-sm font-medium">Report Generated!</span>
              </div>

              {reportData.summary && (
                <div className="bg-muted/50 rounded-lg p-4 space-y-3">
                  <div className="flex justify-between">
                    <span className="text-sm text-muted-foreground">Total Income</span>
                    <span className="text-sm font-medium text-success">
                      ${reportData.summary.income?.toLocaleString()}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-sm text-muted-foreground">Total Expenses</span>
                    <span className="text-sm font-medium text-destructive">
                      ${reportData.summary.expenses?.toLocaleString()}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-sm text-muted-foreground">Balance</span>
                    <span className="text-sm font-medium">
                      ${reportData.summary.balance?.toLocaleString()}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-sm text-muted-foreground">Savings Rate</span>
                    <span className="text-sm font-medium">
                      {reportData.summary.savingsRate}%
                    </span>
                  </div>
                </div>
              )}

              <div className="flex gap-3">
                <Button
                  variant="outline"
                  className="flex-1"
                  onClick={handleDownload}
                >
                  <Download className="h-4 w-4 mr-2" />
                  Download
                </Button>
                <Button
                  variant="outline"
                  className="flex-1"
                  disabled
                  title="Coming soon"
                >
                  <Mail className="h-4 w-4 mr-2" />
                  Email
                </Button>
              </div>
            </div>
          )}

          {reportGenerated && !reportData && (
            <div className="flex items-center gap-2 text-muted-foreground">
              <AlertCircle className="h-4 w-4" />
              <span className="text-sm">No transactions found for this period</span>
            </div>
          )}

          {isError && (
            <div className="flex items-center gap-2 text-destructive">
              <AlertCircle className="h-4 w-4" />
              <span className="text-sm">Failed to generate report</span>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default GenerateReportDialog;